using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Muamalat.Infrastructure.Persistence;

public static class ClientGeneratedKeysConvention
{
    /// <summary>
    /// Every aggregate in this model creates its own identifier with <c>Guid.CreateVersion7()</c>
    /// at construction time, so keys are never default when an entity is new.
    ///
    /// EF Core's default for a Guid key is <c>ValueGeneratedOnAdd</c>, and it then uses "the key
    /// already has a value" as the signal that an entity found in a tracked graph is an existing
    /// row. A newly appended child therefore gets classified as Modified rather than Added: it
    /// produces an UPDATE against a row that does not exist, and in this model it also trips the
    /// append-only guard on the audit trail.
    ///
    /// Declaring the keys as never generated by the store removes the ambiguity. It also matches
    /// what actually happens: PostgreSQL is not generating these values, the domain is.
    ///
    /// Sequential GUIDv7 values are deliberate too. Random GUIDs as primary keys fragment the
    /// index on every insert; version 7 is time ordered, so inserts append rather than scatter.
    /// </summary>
    public static ModelBuilder UseClientGeneratedGuidKeys(this ModelBuilder modelBuilder)
    {
        foreach (var entityType in modelBuilder.Model.GetEntityTypes())
        {
            var key = entityType.FindPrimaryKey();
            if (key is null) continue;

            foreach (var property in key.Properties.Where(p => p.ClrType == typeof(Guid)))
            {
                property.ValueGenerated = ValueGenerated.Never;
            }
        }

        return modelBuilder;
    }
}
