// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Muamalat.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Muamalat.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MuamalatDbContext))]
    [Migration("20260901190137_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Muamalat.Domain.Auditing.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_display_name");

                    b.Property<string>("ActorRoles")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("actor_roles");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("comment");

                    b.Property<int>("EventType")
                        .HasColumnType("integer")
                        .HasColumnName("event_type");

                    b.Property<string>("FromStateCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("from_state_code");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("payload_json");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("previous_hash")
                        .IsFixedLength();

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_request_id");

                    b.Property<string>("ToStateCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("to_state_code");

                    b.Property<string>("TransitionCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("transition_code");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ux_audit_entries_hash");

                    b.HasIndex("ServiceRequestId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_audit_entries_request_sequence");

                    b.ToTable("audit_entries", null, t =>
                        {
                            t.HasComment("Append-only. Updates and deletes are blocked by trigger trg_audit_entries_append_only.");
                        });
                });

            modelBuilder.Entity("Muamalat.Domain.Requests.ServiceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplicantDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("applicant_display_name");

                    b.Property<string>("ApplicantUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("applicant_user_id");

                    b.Property<string>("AssignedToDepartment")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("assigned_to_department");

                    b.Property<string>("AssignedToRole")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("assigned_to_role");

                    b.Property<string>("AssignedToUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("assigned_to_user_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("CurrentStateCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("current_state_code");

                    b.Property<DateTimeOffset>("CurrentStateEnteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_state_entered_at");

                    b.Property<DateTimeOffset?>("DecisionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decision_at");

                    b.Property<bool>("FeePaid")
                        .HasColumnType("boolean")
                        .HasColumnName("fee_paid");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reference_number");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("service_type");

                    b.Property<string>("StateBeforeInformationRequest")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("state_before_information_request");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_definition_id");

                    b.Property<string>("WorkflowKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("workflow_key");

                    b.Property<int>("WorkflowVersion")
                        .HasColumnType("integer")
                        .HasColumnName("workflow_version");

                    b.HasKey("Id")
                        .HasName("pk_service_requests");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_service_requests_reference_number");

                    b.HasIndex("WorkflowDefinitionId")
                        .HasDatabaseName("ix_service_requests_workflow_definition_id");

                    b.HasIndex("ApplicantUserId", "SubmittedAt")
                        .HasDatabaseName("ix_service_requests_applicant");

                    b.HasIndex("AssignedToDepartment", "CurrentStateEnteredAt")
                        .HasDatabaseName("ix_service_requests_open_queue")
                        .HasFilter("closed_at IS NULL");

                    b.HasIndex("WorkflowKey", "CurrentStateCode")
                        .HasDatabaseName("ix_service_requests_open_by_state")
                        .HasFilter("closed_at IS NULL");

                    b.ToTable("service_requests", (string)null);
                });

            modelBuilder.Entity("Muamalat.Domain.Requests.ServiceRequestDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("character varying(127)")
                        .HasColumnName("content_type");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_request_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_path");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("uploaded_by_user_id");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<string>("VerifiedByUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("verified_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_service_request_documents");

                    b.HasIndex("ServiceRequestId", "DocumentType")
                        .HasDatabaseName("ix_service_request_documents_service_request_id_document_type");

                    b.ToTable("service_request_documents", (string)null);
                });

            modelBuilder.Entity("Muamalat.Domain.Workflow.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_en");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_workflow_definitions");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_workflow_definitions_one_published_per_key")
                        .HasFilter("is_published");

                    b.HasIndex("Key", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_definitions_key_version");

                    b.ToTable("workflow_definitions", (string)null);
                });

            modelBuilder.Entity("Muamalat.Domain.Workflow.WorkflowState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_en");

                    b.Property<string>("OwningDepartment")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("owning_department");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_definition_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Sla", "Muamalat.Domain.Workflow.WorkflowState.Sla#SlaPolicy", b1 =>
                        {
                            b1.Property<string>("EscalateToRole")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("sla_escalate_to_role");

                            b1.Property<TimeSpan>("Target")
                                .HasColumnType("interval")
                                .HasColumnName("sla_target");

                            b1.Property<TimeSpan>("WarnAfter")
                                .HasColumnType("interval")
                                .HasColumnName("sla_warn_after");
                        });

                    b.HasKey("Id")
                        .HasName("pk_workflow_states");

                    b.HasIndex("WorkflowDefinitionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_states_workflow_definition_id_code");

                    b.ToTable("workflow_states", (string)null);
                });

            modelBuilder.Entity("Muamalat.Domain.Workflow.WorkflowTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("AllowedRoles")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("allowed_roles");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("FromStateCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("from_state_code");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_en");

                    b.Property<bool>("RequiresComment")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_comment");

                    b.Property<string>("ToStateCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("to_state_code");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_definition_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_transitions");

                    b.HasIndex("WorkflowDefinitionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_transitions_workflow_definition_id_code");

                    b.HasIndex("WorkflowDefinitionId", "FromStateCode")
                        .HasDatabaseName("ix_workflow_transitions_workflow_definition_id_from_state_code");

                    b.ToTable("workflow_transitions", (string)null);
                });

            modelBuilder.Entity("Muamalat.Domain.Auditing.AuditEntry", b =>
                {
                    b.HasOne("Muamalat.Domain.Requests.ServiceRequest", null)
                        .WithMany("AuditTrail")
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_entries_service_requests_service_request_id");
                });

            modelBuilder.Entity("Muamalat.Domain.Requests.ServiceRequest", b =>
                {
                    b.HasOne("Muamalat.Domain.Workflow.WorkflowDefinition", null)
                        .WithMany()
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_requests_workflow_definitions_workflow_definition_id");
                });

            modelBuilder.Entity("Muamalat.Domain.Requests.ServiceRequestDocument", b =>
                {
                    b.HasOne("Muamalat.Domain.Requests.ServiceRequest", null)
                        .WithMany("Documents")
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_request_documents_service_requests_service_request_");
                });

            modelBuilder.Entity("Muamalat.Domain.Workflow.WorkflowState", b =>
                {
                    b.HasOne("Muamalat.Domain.Workflow.WorkflowDefinition", null)
                        .WithMany("States")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_states_workflow_definitions_workflow_definition_id");
                });

            modelBuilder.Entity("Muamalat.Domain.Workflow.WorkflowTransition", b =>
                {
                    b.HasOne("Muamalat.Domain.Workflow.WorkflowDefinition", null)
                        .WithMany("Transitions")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_transitions_workflow_definitions_workflow_definiti");

                    b.OwnsMany("Muamalat.Domain.Workflow.TransitionAction", "Actions", b1 =>
                        {
                            b1.Property<Guid>("WorkflowTransitionId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("Kind");

                            b1.Property<string>("Parameter");

                            b1.HasKey("WorkflowTransitionId", "__synthesizedOrdinal")
                                .HasName("pk_workflow_transitions");

                            b1.ToTable("workflow_transitions");

                            b1
                                .ToJson("actions")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowTransitionId")
                                .HasConstraintName("fk_workflow_transitions_workflow_transitions_workflow_transitio");
                        });

                    b.OwnsMany("Muamalat.Domain.Workflow.TransitionGuard", "Guards", b1 =>
                        {
                            b1.Property<Guid>("WorkflowTransitionId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("Kind");

                            b1.Property<string>("Parameter");

                            b1.HasKey("WorkflowTransitionId", "__synthesizedOrdinal")
                                .HasName("pk_workflow_transitions");

                            b1.ToTable("workflow_transitions");

                            b1
                                .ToJson("guards")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowTransitionId")
                                .HasConstraintName("fk_workflow_transitions_workflow_transitions_workflow_transitio");
                        });

                    b.Navigation("Actions");

                    b.Navigation("Guards");
                });

            modelBuilder.Entity("Muamalat.Domain.Requests.ServiceRequest", b =>
                {
                    b.Navigation("AuditTrail");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Muamalat.Domain.Workflow.WorkflowDefinition", b =>
                {
                    b.Navigation("States");

                    b.Navigation("Transitions");
                });
#pragma warning restore 612, 618
        }
    }
}
